### ISSUE TITLE
Is the starting point and ending point is fixed at 90 degrees? 

### ISSUE THREAD

**Issue by theng616** [MTT-iOS/MTTCircularSlider#3]
Hi,  am i able to change the starting point at other degrees but not only start at 90 degrees?

**Comment by MTT-iOS** [comment]
Yes,you can chang the view.transform to chang the starting point .

**Comment by theng616** [comment]
Thank you so much for the reply. I am a beginner to iOS developing, could you show me the example of the code? For this scenario, i want to the starting point at 180 degrees and the ending point would stop at same as starting point but not 90 degrees. Thank you so much for replying.

**Comment by MTT-iOS** [comment]
`view.transform = CGAffineTransformMakeRotation(180);`

**Comment by theng616** [comment]
It works perfectly, thank you so much!!!
