### ISSUE TITLE
Is the starting point and ending point is fixed at 90 degrees?

### ISSUE THREAD

**Issue by theng616** [MTT-iOS/MTTCircularSlider#4]
Hi, it works with view.transform = CGAffineTransformMakeRotation(180) perfectly with UIColor, but there are having problem when try with selectImage. Is there any other ways to change the starting point and works with selectImage function? I am sorry if i do disturb you.

**Comment by MTT-iOS** [comment]
The view.transform is chang

**Comment by MTT-iOS** [comment]
The view.transform is change view rotation angle,so the image will follow the rotation.You can modify the image file angle to fix the problem .

**Comment by theng616** [comment]
Hi, thank you so much for replying again and again. Do you mean change the image rotation in xcode? If yes, I tried with xcode, UIImageView is able to transform but UIImage doesnt, is there any sample to show?

**Comment by MTT-iOS** [comment]
If you can, you can provide the picture material to me, after I go home will help you solve this problem.

**Comment by MTT-iOS** [comment]
This is my email :2529260592@qq.com.

**Comment by theng616** [comment]
Actually i am testing with your default image, image name: @"select" from Assets.xcassets. Currently the CGAffineTransformMakeRotation of the slider that i am testing now is 40. That would be grateful if you are willing to help me to try solve this problem. Thank you so much.

**Comment by MTT-iOS** [comment]
``` objectivec
view.transform = CGAffineTransformMakeRotation(180) 
```

**Comment by theng616** [comment]
Thank you so much for answering my question again and again. I have just one last question to ask, what i expect from sliding.minValue is the minimum of the value i have set. For example sliding.minValue = 30, sliding.maxValue = 50, so result will shows 30 to 50 in value label, am i right? If i am right, sliding.minValue is not working for me right now, would you help me solve this very very last problem? Thank you so much!!!!!!!

**Comment by theng616** [comment]
For further description, when i set sliding.minValue = 30, will value label shows 30 in 0 degrees?
